name: Deploy Hugo Site to Pages

on:
  # Roda sempre que você der push na branch main
  push:
    branches:
      - main
  # Permite rodar manualmente na aba Actions do GitHub
  workflow_dispatch:

# Permissões para o GITHUB_TOKEN implantar no GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Permite apenas um deploy simultâneo
concurrency:
  group: "pages"
  cancel-in-progress: false

# Configuração padrão do Hugo
env:
  HUGO_VERSION: 0.152.2 # Versão recente

jobs:
  # Tarefa de Construção (Build)
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          submodules: recursive # Importante para baixar o tema PaperMod!
          fetch-depth: 0

      - name: Instalar Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: ${{ env.HUGO_VERSION }}
          extended: true # Versão extendida (melhor compatibilidade)

      - name: Construir o site
        run: hugo --minify

      - name: Upload do artefato
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  # Tarefa de Publicação (Deploy)
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      - name: Webmention Ping Bridgy
        run: |
          curl https://brid.gy/publish/bluesky -d source=https://tiagolima.me/ -d target=https://brid.gy/publish/bluesky
          curl https://brid.gy/publish/mastodon -d source=https://tiagolima.me/ -d target=https://brid.gy/publish/mastodon
